spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diplom_auth
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    user: postgres
    password: root

server.port: @server.port@